### ISSUE TITLE
cannot send data correctly

### ISSUE THREAD

**Issue by lplpkkk** [spring-guides/gs-messaging-stomp-websocket#22]
hello, I am new to this project. I tried to change the "name" to "name1" in the code from send() function in index.html and HelloMessage as follow, but it doesn't work.I am wondering how the GreetingController receive the "name" JSON data?

my code are as follow:
1. send() in index.html

 function send () {
      var name = document.getElementById('name').value;
      client_1.send("/app/sock1",{}, JSON.stringify({ 'name1': name }));
    }

2.HelloMessage.java

package demo;

public class HelloMessage {

    private String name1;

    public String getName() {
        return name1;
    }

}

I also met a problem that I cannot find where the "getContent()" be used in this project?
I tried to rename the function as "getsomething". It can be runned, but showing undefined output.
Where will the project call this function?

please help me with these two problems, I will be very grateful! thank you!

**Comment by rstoyanchev** [comment]
Not knowing the exact failure, I'm guessing but one thing that's clear is the getter on HelloMessage should probably change as well to `getName1`.

**Comment by lplpkkk** [comment]
My GreetingController.java code is as below:

package hello;

import org.springframework.messaging.handler.annotation.MessageMapping;
import org.springframework.messaging.handler.annotation.SendTo;
import org.springframework.stereotype.Controller;

@Controller
public class GreetingController {
    @MessageMapping("/hello")
    @SendTo("/topic/greetings")
    public Greeting greeting(HelloMessage message) throws Exception {
        return new Greeting(message.getName());
    }

}

I am a little confused that why should I change to getName1?Can't I use message.getName() to get name1 value?
Also, I still very confused that where will "getContent()" be called? 

Thank you for your help!!!!

**Comment by gregturn** [comment]
@lplpkkk When you changed the JSON data to {name1: value}, you are asking Jackson to deserialize that to a POJO with an attribute named name1. Jackson works with Java properties, i.e. the getters and setters, so you need to alter your getters/setters to match the new data you configured. By only changing the hidden field to "name1", your POJO has no visible change.

**Comment by gregturn** [comment]
Since this doesn't involve any edits to the guide, I'm going to close the issue. Feel free to continue asking questions though.

**Comment by lplpkkk** [comment]
can I ask after closed?

**Comment by lplpkkk** [comment]
Thank you, Greg! But I am still confused that who call the getcontent() function in this project?
I have deleted this function, and it shows an error when doing doconvert()?
and I also tried to rename "getcontent" to "getQQ", it can be compiled successfully, but showing undefined message.

Thanks for your help!

**Comment by gregturn** [comment]
Why don't you fork this project and push your version of things. That way, it's easier for me to checkout exactly what you did.

**Comment by lplpkkk** [comment]
okay, thanks!

**Comment by lplpkkk** [comment]
https://github.com/lplpkkk/gs-messaging-stomp-websocket/tree/add_fail_data_cell

Here is my code.
(sorry, I am not so familiar with git,too. and my code is a little messy..)

The thing I want to ask is the getContent() function in Greeting.java file.
I mark the getContent() in this version, and it shows some error like this:

ERROR 93932 --- [nboundChannel-3] s.a.s.SimpAnnotationMethodMessageHandler : Unhandled exception

thanks a lot!

**Comment by gregturn** [comment]
Okay, I see where the confusion lies. Essentially the GreetingController returns a Greeting object to the web layer. Jackson, the JSON serialization library used in this guide, converts any Greeting object from a POJO into a JSON structure using Java properties, i.e. getters. (Jackson uses Java setters when converting from JSON to Java).

I don't know all the ins and outs of Jackson, so I don't know what the default behavior is when you have a POJO like your Greeting class with two properties with no getters. I would think it would generate an empty JSON document like {}. I suggest you add standard getters and setters. Then you can sprinkle some console.log() statements inside the JavaScript parts of the web layer to dump out the content that gets sent back from the server.

**Comment by lplpkkk** [comment]
Thank you so much!!
