### ISSUE TITLE
How to set property of the broker such like RabbitMQ?

### ISSUE THREAD

**Issue by lplpkkk** [spring-guides/gs-messaging-stomp-websocket#23]
Hello, I just changed the broker setting to enable my RabbitMQ server works.
(I changed the ""enableSimpleBroker" to "enableStompBrokerRelay" so that RabbitMQ can work in my localhost:15672)

 I am wondering that what should I do if I want to send a message to another PC in the same LAN rather than sending to my local port? 
I guess I might add a java code to set some property with AMQP protocol, but I am not sure how to do that.

thanks for any help or suggestion!

**Comment by rstoyanchev** [comment]
So you have a Web server (Tomcat, Jetty, etc) that exposes a WebSocket endpoint and delegates to RabbitMQ for broadcasting messages. Keep in mind that PCs (clients) are only aware of the WebSocket connection, i.e. they are not connected directly to RabbitMQ. Any client connected to the same server will receive messages. You can also have multiple Web servers all delegating to RabbitMQ for shared messaging/broadcasting.

**Comment by lplpkkk** [comment]
okay, I know that a single server can serve multiple clients. 
I want to know that how to set the port as one of the ConnectionFactory with AMQP in the server side in this project?

still appreciate your response!

**Comment by gregturn** [comment]
I think this is exceeding the scope of his guide. Perhaps posting your queetion on stackoverflow.com would be a better forum to get community feedback.

**Comment by lplpkkk** [comment]
okay, thanks!
