### ISSUE TITLE
How to change exchange type in this project?

### ISSUE THREAD

**Issue by lplpkkk** [spring-guides/gs-messaging-stomp-websocket#24]
I have tried to substitute every '/topic' to '/direct' or '/fanout', but it always shows Received error like this:

 Received ERROR {message=[Unknown destination], content-type=[text/plain], version=[1.0,1.1,1.2], content-length=[145]} session=16d3co4i text/plain payload='/fanout/hello' is not a valid destination.

I think that '/direct', '/fanout', '/topic' all are exchanges created when RabbitMQ server start.So how can't it work ?
I guess maybe the way I subscribe a queue is wrong, still confused.

I have changed two parts in this project as follow:

1.in GreetingController.java

@Controller
public class GreetingController {

    @MessageMapping("/sock1")
    @SendTo("/direct/hello")
    public String greeting(String name) throws Exception {

        return name ;
    }

}

2.in WebSocketConfig.java

@Configuration
@EnableWebSocketMessageBroker
public class WebSocketConfig extends AbstractWebSocketMessageBrokerConfigurer{

  @Override
  public void configureMessageBroker(MessageBrokerRegistry config) {
    config.enableStompBrokerRelay("/fanout");
    config.setApplicationDestinationPrefixes("/app");
  }

  @Override
  public void registerStompEndpoints(StompEndpointRegistry registry) {
    registry.addEndpoint("/sock1").withSockJS();
  } 
}

thanks for your help!

**Comment by gregturn** [comment]
I'm not sure what RabbitMQ has to do with this guide. This guide uses Spring's in-memory message broker.

I checked it out and swapped "/topic" for "/direct" and it works fine. See https://github.com/spring-guides/gs-messaging-stomp-websocket/commit/f450d6b8fad086ca9b5ed43bbad88a45819b8704 as an example.

**Comment by lplpkkk** [comment]
thanks!
