### ISSUE TITLE
Example Does Not Work in Chrome

### ISSUE THREAD

**Issue by SpookieUkie** [spring-guides/gs-messaging-stomp-websocket#26]
I have imported the project into SPS by going File -> New -> Import Spring Getting Started Project.  The sample does work in Firefox, but not in Chrome. For fun, I tried using the latest version of sockjs (1.0.3), but it does  not work in FF or Chrome.

In sockjs 0.3.4, it failed on line 807 
GET http://localhost:8080/hello/info 403 (Forbidden)AbstractXHRObject._start @ sockjs-0.3.4.js:807(anonymous function) @ sockjs-0.3.4.js:841
stomp.js:130 Whoops! Lost connection to undefined

Any help would be appreciated.

**Comment by SpookieUkie** [comment]
It was my fault. I had the CORS plugin running in Chrome...

**Comment by rstoyanchev** [comment]
Note that we do have CORS support (http://docs.spring.io/spring-framework/docs/current/spring-framework-reference/html/websocket.html#websocket-server-allowed-origins).
