### ISSUE TITLE
Not working in Internet Explorer 7,8,9 Seems SockJS fallback mechanism  not working

### ISSUE THREAD

**Issue by venkataraghu** [spring-guides/gs-messaging-stomp-websocket#30]

**Comment by bclozel** [comment]
Could you provide more information about this? What's the exact issue? A connection failure? A JavaScript error?

Are you running the application in the "complete" folder, in the master branch? Or are you deploying this app in another container?

What are the actual HTTP request/responses exchanged here (using IE developer tools or a proxy like Fiddler)?

**Comment by venkataraghu** [comment]
Please ignore this issue. Actually, it is working after i checked "never break on exception" in IE debugger options. I am using IE developer tools to Emulate IE lower versions. with IE9 and lower my debugger was blocking the javascript execution hence i was under an assumption that it is not working.
