### ISSUE TITLE
Why HTML5 WebSocket object can not connect to the server directly?

### ISSUE THREAD

**Issue by XXMY** [spring-guides/gs-messaging-stomp-websocket#32]
`@Configuration`
`@EnableWebSocketMessageBroker`
`public class WebSocketConfig implements WebSocketMessageBrokerConfigurer {`

```
@Override
public void configureMessageBroker(MessageBrokerRegistry config) {
    config.enableSimpleBroker("/topic");
    config.setApplicationDestinationPrefixes("/app");
}

@Override
public void registerStompEndpoints(StompEndpointRegistry registry) {
    registry.addEndpoint("/hello");
}
    // Ingore other empty implements.
```

`}`

HTML5 connection method:
`var websocket = new WebSocket("ws://localhost:8080/hello")`

While `WebSocketMessageBrokerConfigurer` is version of `org.springframework:spring-websocket:4.0.0.RELEASE`, the connection method works fine, but if the version turns to `4.0.1.RELEASE` or newer, there will be an exception like `WebSocket connection to "ws://localhost:8080/hello" failed: Error during WebSocket handshake: Unexpected response code: 403`.

Could anyone tell me why that happens? Thanks a lot!

**Comment by bclozel** [comment]
Are you sure you're running the latest version of the guide?

Or are you asking about a totally different application? If it's not about this guide, please open a new StackOverflow question.
