### ISSUE TITLE
main.css 404

### ISSUE THREAD

**Issue by AChangFeng** [spring-guides/gs-messaging-stomp-websocket#45]
Following this guide: http://spring.io/guides/gs/messaging-stomp-websocket/, I got a 404 when i point my browser at http://localhost:8080.

**Comment by dsyer** [comment]
Works for me. Did you run the code in the `complete` sample?

**Comment by tangwenxu** [comment]
@AChangFeng At fisrt, path "webjars" means resources which included by JAR. so your pom.xml should add those dependencies, like compile/pom.xml. besides, you can reference local resources, by add those resources in your code.
Like this below, I truly have those js and css in the src path.
`<head>
    <title>Hello WebSocket</title>
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/main.css" rel="stylesheet">
    <script src="/js/jquery.min.js"></script>
    <script src="/js/sockjs.min.js"></script>
    <script src="/js/stomp.min.js"></script>
    <script src="/js/app.js"></script>
</head>`
I add prefix path "js" and "css" to show  it works with any prefix expect "webjars".
@dsyer The README.adoc  explains that these dependencies should be added, but not in the right place of the doc.Can i submit to move it to the right place or use local resources? In my opinion, use local resources is friendly for beginner. Beginner can easy understand how it works.

**Comment by dsyer** [comment]
Not quite sure what you mean by "any prefix" - with the code in this project the app works. I have adjusted the listings that show the webjars included in the build (they were pointing to the wrong files). Maybe that makes it more comfortable, and may explain the OP.
