### ISSUE TITLE
Whoops! Lost connection to websocket endpoint

### ISSUE THREAD

**Issue by mhabsaoui** [spring-guides/gs-messaging-stomp-websocket#46]
Hi,

I am working with spring websocket v4.2.3 under Java 1.7.
Deploying is made on Tomcat 7.0 server (without spring-boot).

I just added my websocket server with the file AppWebscoketConfig.java :

@Configuration
@EnableWebSocketMessageBroker
public class AppWebSocketConfig
        extends AbstractWebSocketMessageBrokerConfigurer {
    
    private static final String WEBSOCKET_NAME = "/ws";
    
    @Override
    public void configureMessageBroker(final MessageBrokerRegistry config) {
        config.enableSimpleBroker();
        config.setApplicationDestinationPrefixes();
    }
    
    @Override
    public void registerStompEndpoints(final StompEndpointRegistry registry) {
        registry.addEndpoint(WEBSOCKET_NAME).setAllowedOrigins("*").withSockJS();
    }
}
I also added the 2 required dependencies :

		
		<dependency org="org.springframework" name="spring-websocket" rev="4.2.3.RELEASE"/>
		<dependency org="org.springframework" name="spring-messaging" rev="4.2.3.RELEASE"/>	
So after I ran my Spring App, I get the MessageBroker running and websocket server ready, according to those info logs :

> INFO 15:59:22,515 BrokerAvailabilityEvent[available=true, SimpleBrokerMessageHandler [DefaultSubscriptionRegistry[cache[0 destination(s)], registry[0 sessions]]]]
> 
> INFO 13:38:12,424 WebSocketSession[0 current WS(0)-HttpStream(0)-HttpPoll(0), 0 total, 0 closed abnormally (0 connect failure, 0 send limit, 0 transport error)], stompSubProtocol[processed CONNECT(0)-CONNECTED(0)-DISCONNECT(0)], stompBrokerRelay[null], inboundChannel[pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], outboundChannelpool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], sockJsScheduler[pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]

Front JS code :

        function connect() {
        	var socket = new SockJS('/ws');
        	stompClient = Stomp.over(socket);
        	stompClient.connect({}, function (frame) {
        		stompClient.debug('[DEBUG] Connected to websocket server: ' + frame);        		
        	});
        }
But, The thing is my websocket server is unreachable (no log on Back-end side from server, only on Front...) =>

> Opening Web Socket...
> GET http://localhost:8080/ws/info?t=1536733706374 404 (Introuvable)
> Whoops! Lost connection to http://localhost:8080/ws

I tried almost all possibilities : modifying web.xml, checked Spring-security, added XML version of websocker server, checked URLs and Endpoint's possible context paths, chrome extension APIC Client testing for websocket, tried latest Stomp/Sock JS libs with index.html....

About web.xml :

```
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://java.sun.com/xml/ns/javaee" xmlns:web="http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd"
	xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd" version="3.0"
	metadata-complete="true">

	<context-param>
		<param-name>jndiPropertySourceEnabled</param-name>
		<param-value>true</param-value>
	</context-param>
	
	<context-param>
		<param-name>contextConfigLocation</param-name>
		<param-value>
					classpath:net/bull/javamelody/monitoring-spring-datasource.xml
					/WEB-INF/applicationContext-service.xml
		</param-value>
	</context-param>

		<filter>
                <filter-name>monitoring</filter-name>
                <filter-class>net.bull.javamelody.MonitoringFilter</filter-class>
        </filter>
        <filter-mapping>
                <filter-name>monitoring</filter-name>
                <url-pattern>/*</url-pattern>
        </filter-mapping>
        <listener>
                <listener-class>net.bull.javamelody.SessionListener</listener-class>
        </listener>
        
        
	<listener>
		<listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>
	</listener>
	<listener>
		<listener-class>org.springframework.web.context.request.RequestContextListener</listener-class>
	</listener>
	<servlet>
		<servlet-name>guir-servlet</servlet-name>
		<servlet-class>com.sun.jersey.spi.spring.container.servlet.SpringServlet</servlet-class>
		<init-param>
			<param-name>com.sun.jersey.config.property.packages</param-name>
			<param-value>com.pg.services.provider;com.pg.processus.provider.json;com.pg.guir.doc;com.wordnik.swagger.jaxrs.listing</param-value>
		</init-param>
		<!-- Pour compléter avec la javadoc -->
		<init-param>
			<param-name>com.sun.jersey.spi.container.ContainerResponseFilters</param-name>
			<param-value>com.pg.guir.servlet.CrossDomainFilter</param-value>
		</init-param>
		<init-param>
			<param-name>com.sun.jersey.api.json.POJOMappingFeature</param-name>
			<param-value>1</param-value>
		</init-param>
		<init-param>
			<param-name>com.sun.jersey.config.feature.DisableXmlSecurity</param-name>
			<param-value>1</param-value>
		</init-param>	
		<!-- init-param>
			<param-name>swagger.api.basepath</param-name>
			<param-value>http://localhost:8080/guir/rest</param-value>
		</init-param-->
		<init-param>
			<param-name>api.version</param-name>
			<param-value>1.0</param-value>
		</init-param>
		<init-param><!-- Mapping des extensions .xml et .json dans les requêtes pour les associer au bon type de media -->
            <param-name>com.sun.jersey.config.property.MediaTypeMappings</param-name>
            <param-value>xml : application/xml, json : application/json, pdf : application/pdf</param-value>
        </init-param>
		<load-on-startup>1</load-on-startup>
	</servlet>
	<servlet>
		<servlet-name>Bootstrap</servlet-name>
		<servlet-class>com.pg.guir.servlet.Bootstrap</servlet-class>
		<load-on-startup>1</load-on-startup>
	</servlet>
	<servlet-mapping>
		<servlet-name>guir-servlet</servlet-name>
		<url-pattern>/rest/*</url-pattern>
	</servlet-mapping>
	
	<!-- Filtre Spring Security -->
	<filter>
		<filter-name>springSecurityFilterChain</filter-name>
		<filter-class>org.springframework.web.filter.DelegatingFilterProxy</filter-class>
	</filter>
	<filter-mapping>
		<filter-name>springSecurityFilterChain</filter-name>
		<url-pattern>/*</url-pattern>
	</filter-mapping>

</web-app>
```

Always testing under Chrome (even Firefox).

I don't see what I am doing wrong or missing, and have no more clue where to look :/

Any help is welcome.

**Comment by rstoyanchev** [comment]
Please note that the 4.2.x branch is not supported and for security reasons alone you should be on the current long term maintenance branch 4.3.x (4.3.19 is the latest release on that branch).

Aside from that this is not a place to ask general questions. Please use StackOverflow. My best guess is that the URL you're using from the client side is incorrect.
