### ISSUE TITLE
Why create a new TCP connection to MQ for each JS client? 

### ISSUE THREAD

**Issue by rockywebasm** [spring-guides/gs-messaging-stomp-websocket#48]
We build an application like webchat, use ActiveMQ as the broker, when one browser client connect to chat server, we find that a new TCP connection for MQ, so if we want to support millions client, it may create too many connections for MQ, can we reuse the connection between chat server and MQ?

**Comment by gregturn** [comment]
This guide has nothing to do with any MQ broker. Please open usage questions on stackoverflow.com.
