### ISSUE TITLE
EnableAutoConfiguration is explained in guide but not used in code

### ISSUE THREAD

**Issue by ge0ffrey** [spring-guides/gs-messaging-stomp-websocket#49]
On this url https://spring.io/guides/gs/messaging-stomp-websocket/
it shows code like this:

```
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
```
and then explains this, which isn't used in that code:

```
@EnableAutoConfiguration tells Spring Boot to start adding beans based on classpath settings, other beans, and various property settings.
```

**Comment by dsyer** [comment]
It is used in the code though, the full text actually explains "`@SpringBootApplication` is a convenience annotation that adds all of the following..." and then a list which includes `@EnableAutoConfiguration`. Looks like this is fine to me.

**Comment by ge0ffrey** [comment]
Agreed.
