### ISSUE TITLE
Undefined value in connect() function

### ISSUE THREAD

**Issue by idedaloc** [spring-guides/gs-messaging-stomp-websocket#51]
Problem.
Following the guide, I got a undefined value for the expected greeting upon been connected to the websocket service. Debugging I have found that it is a problem in the connect() function of the app.js file, in the next line, 

22: showGreeting(JSON.parse(greeting.body).content);

Solution that works for me.
Using the property to be displayed and also the one that is coming as a json property, which it is "greeting", in the connect() function, solve the problem for me:

showGreeting(JSON.parse(greeting.body).greeting);

If there is any other explanation about this, or in case of any comment, please let me know.

**Comment by dsyer** [comment]
`Greeting` has a single property called "content", so the code works for me as it is. Maybe you created a different version of `Greeting.java`? Or maybe this issue is so old someone fixed it and forgot to close it.
