### ISSUE TITLE
Unable to find webjars/jquery after packagin

### ISSUE THREAD

**Issue by ChuckBTaylor** [spring-guides/gs-messaging-stomp-websocket#57]
After packagin and executing the jar, I can see the below error in the console:
GET http://localhost:8080/webjars/jquery/jquery.min.js net::ERR_ABORTED 404

I am getting this issue after cloning down the repo from the "Using WebSocket to build an interactive web application" on spring.io

**Comment by peeyushsharma** [comment]
I couldn’t make webjars works . So i changed index.html as follows to make it work
` <script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" type="text/javascript" ></script>
    <script src="https://cdn.jsdelivr.net/npm/sockjs-client@1.4.0/dist/sockjs.min.js" type="text/javascript" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/stomp.js/2.3.3/stomp.min.js" type="text/javascript"></script>`

**Comment by bonaluo** [comment]
I have the same problem. You can upgrade org.webjars: jQuery to the latest version

**Comment by dsyer** [comment]
duplicates #59
