### ISSUE TITLE
add @SendToUser demo

### ISSUE THREAD

**Issue by DLX4** [spring-guides/gs-messaging-stomp-websocket#62]
I think it will be better to add a demo describe how to use @SendToUser. It will meet the needs of more people.

**Comment by Rajat-Jain29** [comment]
Hello ,
I have one doubt like I want to send the data or pushes the data to websocket . how can I do that ?
like There is one service in I hit that service then all the data is send to websocket I want this is it possible to send all the data to websocket in spring boot ?
Please help me .
Thanks in advance.

**Comment by Buzzardo** [comment]
We keep the guides very simple, because we target 15 minutes to complete them. This adds more complexity than we want. It would make good blog post that you could share with the Spring community.
