### ISSUE TITLE
Running Project with Gradle in Intellij

### ISSUE THREAD

**Issue by bigalnz** [spring-guides/gs-messaging-stomp-websocket#81]
I forked and cloned the repo then opened the project using from Version control option in Intellij.

None of the dependencies are recognised.

I have tried the refresh wheel in the gradle window.

**Comment by robertmcnees** [comment]
Hi @bigalnz. If you're having difficulty with importing to IntelliJ perhaps [this video from Spring Academy](https://spring.academy/guides/spring-setup-intellij-idea-community-edition) could help?

Our CI build in GitHub Actions is currently green, so I'm thinking that is only a problem with your local IDE integration. If you think there is a larger issue with the code please reply and we can reopen the issue and continue the discussion. I'll close the issue for now.
